# Generated by Django 3.0.3 on 2020-02-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(max_length=5, verbose_name='分数')),
                ('user_name', models.CharField(max_length=64, verbose_name='客户端id')),
            ],
        ),
    ]
